name: NuGet Package Publishing

# This workflow runs when you create a new release
on:
  release:
    types: [published]
  
  # Allow manual triggering for testing
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to NuGet?'
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            8.0.x
            9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Create NuGet Package
        run: dotnet pack BetterBuffers/BetterBuffers.csproj --configuration Release --no-build -o nupkg

      - name: Publish to NuGet
        # Only publish on actual releases (not on manual workflow runs, unless specified)
        if: ${{ github.event_name == 'release' || github.event.inputs.publish == 'true' }}
        run: dotnet nuget push nupkg/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

      - name: Upload NuGet package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: nupkg/*.nupkg